// Generated by scripts/env.js at build time — do not edit manually
export const environment = {
  production: true,
  supabaseUrl: '',
  supabaseAnonKey: '',
  lsStoreSlug: '',
  lsProductId: '',
  lsVariantId: '',
};
